### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by GecraftetHD** [cryptic-game/frontend#236] opened 2021-01-26 19:32 UTC
![Login Bug](https://user-images.githubusercontent.com/77395698/105894884-10f4f200-6015-11eb-968f-46f7fce335b5.gif)

If you want to log in, into the official frontend and you have zoomed the website out, on the edge of the screen, there appear weird green stripes ;D

Happened to me on firefox and zoom on 70 %

**Comment by Tert0** [comment] 2021-02-02 15:47
Console Log:
![image](https://user-images.githubusercontent.com/62036464/106624849-60d43b80-6576-11eb-91e0-c6d0f5828250.png)

**Comment by Tert0** [comment] 2021-02-02 15:48
I found this: https://github.com/beyondcode/laravel-websockets/issues/382#issuecomment-631569344

**Comment by Tristan-H11** [comment] 2021-02-07 11:10
Tested it on firefox 85.0.1 (64-Bit) and couldn't reproduce it.
It just loops the bg on my machine 
![grafik](https://user-images.githubusercontent.com/45330667/107144732-6eeed700-693d-11eb-8475-2eea68de237b.png)

**Comment by JannikEmmerich** [comment] 2021-02-20 23:42
Unfortunately I cannot reproduce this as well. Please give us your exact browser version so we can have a further look into the bug.

**Comment by GecraftetHD** [comment] 2021-02-22 14:58
Happens to me on firefox 85.0.2 64 bit

**Comment by JannikEmmerich** [comment] 2021-02-22 15:14
To reproduce this: Reload the page while zoomed out.

**Comment by Tristan-H11** [comment] 2022-03-06 12:19
Fixed with 1344edf8040c435ecf4de25137b0f5b58b70d558.

**Closed by Tristan-H11** 2022-03-06 12:19 UTC
Labels: bug
